### ISSUE TITLE
Fix css bundle output

### ISSUE THREAD

**Issue by musangowope** [bonlineza/b-lib#32]
When using  a component from `b-lib`, the component's styling in the node module is not being detected and if you try import bundle.css from `import @bonlineza/b-lib/build/bundle.css` I run into this issue..

```
ERROR in ../b-lib/build/bundle.css 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
```

**Comment by robguy21** [comment]
should be fixed with

```js
// webpack.config.base.js
  module: {
    rules: [
      // this is the correct loader for css files
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader'],
      },
    ]
  },
```

...in the relevant project's webpack setup
