### ISSUE TITLE
Functions Library

### ISSUE THREAD

**Issue by sscholle** [bonlineza/b-lib#41]
## User Story
**As a**: developer

**I want to**: have access the a variety of re-useable functions across all our projects

**Because**: we have several copies these functions living in various projects which don't have tests and exist in various states of development

## Additional Context
_Add any context, screenshots, designs, links, etc. about the feature request here._
https://github.com/bonlineza/luxity-sales/pull/151#pullrequestreview-289992569
note that some functions are project specific - please list functions that should be migrated here in the Acceptance Criteria

## Acceptance Criteria
_List of conditions that mark the story as complete_
- [x] move un-opinionated and shared functions to library
- [x] tests to be written for EACH function added to the library 
- [x] documentation for each function - jsdoc (@return, @params, @description)
- [x] smoothScrollTo
- [x] constrainable
- [ ] etc, list them out here first...

### Edge cases
_List of edge cases to be considered when marking the story as complete_
- [ ] project usages must be updated to use the new library location

----

## Technical Description (not required initially)
_A technical description of the problem, this should be completed by the engineering manager/developer_
function/files under the `functions` folders in projects should be migrated to the library (if they are seen as needed in many projects)

**Comment by musangowope** [comment]
These are the list of opinionated functions which I have identified from ASSA and Luxity:
## Assa:

### Simple Functions 
- debounced [needs test],
- constructObjectFromString: [has test]
- filterByDataFields [has test]
- filterObjProps: [has test],
- flattenObject: [has test],
- formatDate: [needs test],
- formatDateWithMoment: [needs test],
- getArrayElementByPropVal: [needs test]
- getToken: [needs test],
- hasOwn: [needs test],
- hasValue: [needs test],
- moveItemInArray: [needs test],
- stringFormatting: [needs test],
- stringOccurances: [needs test],
- throttler: [needs test]
- sortByColumn: [has test]


### Complex Functions:
- actionRequest [needs test]
- authenticator [needs test]
- constrainable [needs test]
- getNextRoute [needs test]
- searchQueryParams [needs test]
- setQueryParameters [needs test]




## Luxity Sales/ Luxity Front:
### Simple Functions:
- formatInNumberInZar: [Needs test]
- convertUnixTimeToDat: [Needs test]
- mapOrFalse: [Needs test]
- validateEmail: [Needs test]
- removeWhiteSpac: [Needs test] 
- compareObjWithDefault: [Needs test]
- getAxiosRequestInstance: [Needs test]

**Comment by sscholle** [comment]
i don't think we will manage to get all of the listed functions into the library this sprint, however we must fix the existing ones in the library already and try to also add `smoothScrollTo` add `constrainable`
