### ISSUE TITLE
Component Class Descriptions

### ISSUE THREAD

**Issue by sscholle** [bonlineza/b-lib#63]
## User Story
**As a**: Developer

**I want to**: understand the purpose of the components

**Because**: i cant reliably understand the usefulness by its name alone

## Additional Context
_Add any context, screenshots, designs, links, etc. about the feature request here._

## Acceptance Criteria
_List of conditions that mark the story as complete_
- [x] write docblocks for each components `Class`
- [x] ensure the blocks are rendered in the generated markdown files

### Edge cases
_List of edge cases to be considered when marking the story as complete_
- [ ]

----

## Technical Description (not required initially)
_A technical description of the problem, this should be completed by the engineering manager/developer_

**Comment by robguy21** [comment]
Might be worth implementing - https://www.npmjs.com/package/eslint-plugin-jsdoc

**Comment by sscholle** [comment]
i thin in this case, jsdoc for classes isn't that useful as the description and the props are the most important aspect. But obviously for function documentation, it's usually better to go the 'jsdoc' route in my opinion.
